orbs:
  docker: circleci/docker@1.5.0

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  docker-publisher:
    # environment:
    #   IMAGE_NAME: ndukwearm19docker/docker-node-app
    docker: # Each job requires specifying an executor
      - image: cimg/node:17.3.0

jobs:
  buildDockerImg:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Docker Image for Deployment"
          command: |
            npm run build
            curl https://sdk.cloud.google.com > install.sh
            bash install.sh --disable-prompts
            export PATH=/home/circleci/google-cloud-sdk/bin:$PATH;
            echo ${GCLOUD_SERVICE_KEY} > ${HOME}/account-auth.json
            gcloud auth activate-service-account circleci-docker-build@db8bot.iam.gserviceaccount.com --key-file=${HOME}/account-auth.json
            gcloud auth configure-docker us-central1-docker.pkg.dev
            export IMGNAME=$(node -p "require('./package.json').scripts.build.replace('docker build . -t ','')")
            docker tag "$IMGNAME" us-central1-docker.pkg.dev/db8bot/discord-db8bot/"$IMGNAME"
            docker push us-central1-docker.pkg.dev/db8bot/discord-db8bot/"$IMGNAME"
            gcloud compute ssh discord-db8bot-host --zone=us-central1-a --command="docker system prune -f" --quiet --project=db8bot
            gcloud compute instances update-container discord-db8bot-host --project=db8bot --container-image=us-central1-docker.pkg.dev/db8bot/discord-db8bot/"$IMGNAME" --container-env=DOPPLER_TOKEN="${DOPPLER_TKN}" --container-restart-policy=always


workflows:
  build-for-deployment:
    jobs:
      - buildDockerImg:
          filters:
            tags:
              only: ^[0-9]+(\.[0-9]+)*$
